import { Injectable, NotFoundException } from '@nestjs/common';import { Store } from '../common/store';import { TimelineEvent } from '../common/types';
@Injectable() export class TimelineService{constructor(private readonly store:Store){}get(companyId:string,upiId:string,options:{page:number;pageSize:number;type?:string}={page:1,pageSize:30}){if(!this.store.upis.some(u=>u.id===upiId&&u.companyId===companyId))throw new NotFoundException('UPI no encontrada');const e:TimelineEvent[]=[];const add=(v:TimelineEvent)=>e.push(v);
this.store.observations.filter(x=>x.companyId===companyId&&x.upiId===upiId).forEach(x=>add({id:`OBS-${x.id}`,upiId,type:'OBSERVATION',occurredAt:x.observedAt,title:'Observación de campo',summary:x.description,severity:x.severity,sourceId:x.id,relatedIds:{observationId:x.id}}));
this.store.readings.filter(x=>x.companyId===companyId&&x.upiId===upiId).forEach(x=>add({id:`READ-${x.id}`,upiId,type:'READING',occurredAt:x.measuredAt,title:x.variableCode,summary:`${x.value} ${x.unit} · confianza ${x.confidence}%`,sourceId:x.id,relatedIds:{readingId:x.id}}));
this.store.irrigations.filter(x=>x.companyId===companyId&&x.upiId===upiId).forEach(x=>add({id:`IRR-${x.id}`,upiId,type:'IRRIGATION',occurredAt:x.startAt,title:'Riego registrado',summary:`${x.grossDepthMm} mm · ${x.appliedVolumeL} L`,sourceId:x.id,relatedIds:{irrigationId:x.id}}));
this.store.alerts.filter(x=>x.companyId===companyId&&x.upiId===upiId).forEach(x=>add({id:`ALT-${x.id}`,upiId,type:'ALERT',occurredAt:x.detectedAt,title:x.title,summary:x.description,severity:x.severity,sourceId:x.id,relatedIds:{alertId:x.id}}));
this.store.recommendations.filter(x=>x.companyId===companyId&&x.upiId===upiId).forEach(x=>add({id:`REC-${x.id}`,upiId,type:'RECOMMENDATION',occurredAt:x.createdAt,title:'Recomendación',summary:x.actionDescription,severity:x.priority,sourceId:x.id,relatedIds:{recommendationId:x.id}}));
this.store.processes.filter(x=>x.companyId===companyId&&x.upiId===upiId).forEach(x=>add({id:`PROC-${x.id}`,upiId,type:'PROCESS',occurredAt:x.openedAt,title:x.title,summary:`${x.objective} · ${x.status}`,severity:x.priority,sourceId:x.id,relatedIds:{processId:x.id,recommendationId:x.recommendationId}}));
this.store.tasks.filter(x=>x.companyId===companyId&&x.upiId===upiId).forEach(x=>add({id:`TASK-${x.id}`,upiId,type:'TASK',occurredAt:x.dueAt,title:x.title,summary:`${x.status} · evidencias ${x.evidenceCount}`,severity:x.priority,sourceId:x.id,relatedIds:{taskId:x.id,processId:x.processId}}));
this.store.evidence.filter(x=>x.companyId===companyId&&x.upiId===upiId).forEach(x=>add({id:`EVD-${x.id}`,upiId,type:'EVIDENCE',occurredAt:x.capturedAt,title:`Evidencia ${x.phase??''}`.trim(),summary:x.description??x.originalFilename,sourceId:x.id,relatedIds:{evidenceId:x.id,processId:x.processId,taskId:x.taskId}}));
this.store.processFollowUps.filter(x=>x.companyId===companyId).filter(x=>this.store.processes.some(p=>p.id===x.processId&&p.upiId===upiId)).forEach(x=>add({id:`FUP-${x.id}`,upiId,type:'FOLLOW_UP',occurredAt:x.completedAt??x.dueAt,title:'Seguimiento agronómico',summary:`${x.status} · ${x.variables.join(', ')}`,sourceId:x.id,relatedIds:{followUpId:x.id,processId:x.processId}}));
this.store.processOutcomes.filter(x=>x.companyId===companyId).filter(x=>this.store.processes.some(p=>p.id===x.processId&&p.upiId===upiId)).forEach(x=>add({id:`OUT-${x.id}`,upiId,type:'OUTCOME',occurredAt:x.evaluatedAt,title:'Resultado técnico',summary:`${x.status} · confianza ${x.confidence}%`,severity:x.status==='ADVERSE'?'CRITICAL':undefined,sourceId:x.id,relatedIds:{outcomeId:x.id,processId:x.processId}}));
const sorted=e.sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));const filtered=options.type?sorted.filter(x=>x.type===options.type):sorted;const page=Math.max(1,Number.isFinite(options.page)?options.page:1);const pageSize=Math.min(100,Math.max(1,Number.isFinite(options.pageSize)?options.pageSize:30));const start=(page-1)*pageSize;return{items:filtered.slice(start,start+pageSize),pagination:{page,pageSize,totalItems:filtered.length,totalPages:Math.max(1,Math.ceil(filtered.length/pageSize))}};}}
